In [2]:
import numpy as np
rng1=np.random.default_rng()
rng1.random()

0.9172036479824403

In [3]:
rng2=np.random.default_rng()
rng2.random()

0.8919284169036918

In [4]:
rng=np.random.default_rng()
rng.random()

0.6857125145129602

In [5]:
rng.standard_normal(10)

array([-0.48214994,  1.20933078,  0.31450317, -0.53832552, -0.07034746,
        0.05516378, -0.17798465, -1.81861509, -0.32469948, -1.17765143])

In [6]:
rng.integers(low=0, high=10, size=5)

array([2, 3, 7, 6, 1])

In [7]:
import numpy as np
import secrets
secrets.randbits(128)

262072296326689207150409118103287736962

In [8]:
rng11=np.random.default_rng(37263097010480016776552086208060604907)
rng11.random()

0.12225809165448365

In [9]:
rng22=np.random.default_rng(37263097010480016776552086208060604907)
rng22.random()

0.12225809165448365

In [10]:
rngA = np.random.default_rng(100)
rngA.random()


0.8349816305020089

In [11]:
rngB = np.random.default_rng(101)
rngB.random()


0.9435325056105539

In [17]:
import numpy as np
rng12345 = np.random.default_rng(12345)
print (rng12345)

Generator(PCG64)


In [25]:
rfloat = rng12345.random()
rfloat

0.5983087535871898

In [23]:
type(rfloat)

float

In [26]:
rints = rng12345.integers(low=0, high=10, size=3)
rints

array([2, 1, 2])

In [28]:
type(rints[0])

numpy.int64

In [33]:
rng3= np.random.default_rng(seed=42)
arr1= rng3.random((3, 3))
arr1

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

In [34]:
type(arr1)

numpy.ndarray

In [35]:
type(rng3)

numpy.random._generator.Generator