In [3]:
import numpy as np
rng1=np.random.default_rng()
rng1.random()

0.7149634162541748

In [4]:
rng2=np.random.default_rng()
rng2.random()

0.25542335224244295

In [5]:
rng=np.random.default_rng()
rng.random()

0.4817653048728886

In [6]:
rng.standard_normal(10)

array([-0.88164365,  0.20486425, -1.26570908, -0.72585308,  0.28147457,
       -0.40094748,  0.94328574,  0.76301676, -1.21229127,  1.96389706])

In [7]:
rng.integers(low=0, high=10, size=5)

array([3, 5, 9, 0, 3])

In [8]:
import numpy as np
import secrets
secrets.randbits(128)

116521164198801556265929360000179858183

In [9]:
rng11=np.random.default_rng(37263097010480016776552086208060604907)
rng11.random()

0.12225809165448365

In [10]:
rng22=np.random.default_rng(37263097010480016776552086208060604907)
rng22.random()

0.12225809165448365

In [11]:
rngA = np.random.default_rng(100)
rngA.random()


0.8349816305020089

In [12]:
rngB = np.random.default_rng(101)
rngB.random()


0.9435325056105539

In [13]:
import numpy as np
rng12345 = np.random.default_rng(12345)
print (rng12345)

Generator(PCG64)


In [14]:
rfloat = rng12345.random()
rfloat

0.22733602246716966

In [15]:
type(rfloat)

float

In [16]:
rints = rng12345.integers(low=0, high=10, size=3)
rints

array([7, 3, 2])

In [17]:
type(rints[0])

numpy.int64

In [18]:
rng3= np.random.default_rng(seed=42)
arr1= rng3.random((3, 3))
arr1

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

In [19]:
type(arr1)

numpy.ndarray

In [20]:
type(rng3)

numpy.random._generator.Generator

In [21]:
import numpy as np
rng33= np.random.default_rng(seed=22)
arr11= rng33.random((3, 3))
arr11

array([[0.36634692, 0.19929538, 0.08855837],
       [0.65319169, 0.45933704, 0.98767562],
       [0.85156807, 0.83696132, 0.05143877]])

In [22]:
rng333= np.random.default_rng(seed=22)
arr111= rng333.random((3, 3))
arr111

array([[0.36634692, 0.19929538, 0.08855837],
       [0.65319169, 0.45933704, 0.98767562],
       [0.85156807, 0.83696132, 0.05143877]])

In [23]:
if(rng33 == rng333):
    print("Both Seeds same")
else:
    print("Both Seeds different")

Both Seeds different
